version: "3.6"

services:

  gcp-scaffold-svc:
    image: sixeyed/app-template-gcp-gcp-svc
    build:
      context: ./services/gcp

  gke-scaffold-svc:
    image: sixeyed/app-template-gcp-gke-svc
    build:
      context: ./services/gke

  redis-leader-scaffold-svc:
    image: sixeyed/app-template-gcp-redis-leader-svc
    build:
      context: ./services/redis-leader

  redis-follower-scaffold-svc:
    image: sixeyed/app-template-gcp-redis-follower-svc
    build:
      context: ./services/redis-follower

  guestbook-php-scaffold-svc:
    image: sixeyed/app-template-gcp-guestbook-php-svc
    build:
      context: ./services/guestbook-php