apiVersion: v1alpha1
generated: "2018-06-13T09:24:07.392654524Z"
kind: RepositoryContent
services:
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: gcp
    platforms:
      - linux
  spec:
    description: Google Cloud Platform
    icon: https://raw.githubusercontent.com/sixeyed/app-template-gcp/master/img/gcp.png
    source:
      image: sixeyed/app-template-gcp-gcp-svc
    title: GCP 
    parameters:
    - name: project
      description: Project
      type: string
    - name: zone
      description: Zone
      type: string
    - name: saKeyEncoded
      description: Service Account encoded key
      type: string
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: gke
    platforms:
      - linux
  spec:
    description: Google Kubernetes Engine
    icon: https://raw.githubusercontent.com/sixeyed/app-template-gcp/master/img/gke.png
    source:
      image: sixeyed/app-template-gcp-gke-svc
    title: GKE
    parameters:
    - name: gkeTemplate
      description: Cluster template
      type: enum
      values:
      - value: "Your first cluster"
        description: "Your first cluster"
      - value: "Standard cluster"
        description: "Standard cluster"
      - value: "Highly available"
        description: "Highly available"
    - name: kubeVersion
      description: Kubernetes version
      type: enum
      values:
      - value: "1.13.7-gke.8"
        description: "1.13.7-gke.8"
      - value: "1.12.8-gke.10"
        description: "1.12.8-gke.10"
    - name: nodeCount
      type: enum
      values:
      - value: "2"
        description: "2"
      - value: "3"
        description: "3"
      - value: "5"
        description: "5"
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: redis-master
    platforms:
      - linux
  spec:
    description: An in-memory data structure store
    icon: https://raw.githubusercontent.com/sixeyed/app-template-gcp/master/img/redis-master.png
    source:
      image: sixeyed/app-template-gcp-redis-master-svc
    title: Redis Master
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: redis-slave
    platforms:
      - linux
  spec:
    description: Redis replicated slaves
    icon: https://raw.githubusercontent.com/sixeyed/app-template-gcp/master/img/redis-slave.png
    source:
      image: sixeyed/app-template-gcp-redis-slave-svc
    title: Redis Slave
    parameters:
    - name: replicas
      description: Replicas
      type: string
      defaultValue: "2"
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: guestbook-php
    platforms:
      - linux
  spec:
    description: Guestbook sample app (PHP)
    icon: https://raw.githubusercontent.com/sixeyed/app-template-gcp/master/img/php.png
    source:
      image: sixeyed/app-template-gcp-guestbook-php-svc
    title: Guestbook
    parameters:
    - name: externalPort
      defaultValue: "8080"
      description: External port      
      type: hostPort
    - name: replicas
      description: Replicas
      type: string
      defaultValue: "3"
templates:
- apiVersion: v1alpha1
  kind: ApplicationTemplate
  metadata:
    name: gcp-guestbook-php
    platforms:
    - linux
  spec:
    description: Guestbook sample app running on GKE
    services:
    - name: Google Cloud Platform
      serviceId: gcp
      parameters:
        zone: us-central1-a
    - name: Google Kubernetes Engine
      serviceId: gke
      parameters:
        kubeVersion: 1.13.7-gke.8
        nodeCount: 2
    - name: Redis Master
      serviceId: redis-master 
    - name: Redis Slave
      serviceId: redis-slave 
    - name: Guestbook (PHP)
      serviceId: guestbook-php
    title: Guestbook sample app running on GKE